#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

if [ -z "$DEV_ENV" ]; then
    echo "ERROR: Environment variable DEV_ENV needs to be set to the path of this repository."
    exit 1
fi

export DEV_ENV="$DEV_ENV"

grep_pattern=""
dry_run="0"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry)
            dry_run="1"
            shift 
            ;;
        *)
            if [ -n "$grep_pattern" ]; then
                echo "ERROR: Only one filter pattern allowed."
                exit 1
            fi
            grep_pattern="$1"
            shift 
            ;;
    esac
done

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

if [[ $dry_run == "1" ]]; then
    log "Dry run enabled. Scripts will not be executed."
fi
log "Using DEV_ENV: $DEV_ENV"
log "Filter pattern: '$grep_pattern'"
log "Looking for tasks in: $script_dir/runs"

runs_dir="$script_dir/runs"

if [ ! -d "$runs_dir" ]; then
    log "Runs directory not found: $runs_dir"
    exit 0 
fi

find "$runs_dir" -mindepth 1 -maxdepth 1 -executable -print0 | while IFS= read -r -d $'\0' s; do
    script_basename=$(basename "$s")

    if [ -n "$grep_pattern" ]; then
        if echo "$script_basename" | grep -vq "$grep_pattern"; then
            log "Filter '$grep_pattern' skipped: $script_basename"
            continue 
        fi
        log "Filter '$grep_pattern' matched: $script_basename"
    fi

    log "Running task script: $s"

    if [[ $dry_run == "0" ]]; then
        "$s"
    fi
done

log "Task runner finished."


