#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
selected=$(find ~ -maxdepth 3 \
    \( -path ~/paru -o -path ~/.git -o -path ~/node_modules -o -path ~/.cache -o -path ~/.cargo -o -path ~/.zen -o -path ~/.mozilla \) -prune -o \
    \( -type f -o -type d \) -print \
    | fzf --preview 'if [ -d {} ]; then eza --tree --color=always {} | head -200; else bat -n --color=always --line-range :500 {}; fi')
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s "$selected_name" -c "$selected"
    exit 0
fi

if [[ -z $TMUX ]]; then
    if ! tmux has-session -t="$selected_name" 2>/dev/null; then
        tmux new-session -ds "$selected_name" -c "$selected"
    fi
    tmux switch-client -t "$selected_name"
    exit 0
fi

tmux new-window -c "$selected" -n "$selected_name"

